fiman/blueprints/backend.py
from flask import Blueprint, render_template, request, current_app, flash, redirect, url_for
from flask_login import login_required

from fiman.extensions import db
from fiman.models import Transaction, Account, Project
from fiman.forms import PostForm
from fiman.utils import redirect_back

backend_bp = Blueprint('backend', __name__)

@backend_bp.before_request
@login_required
def login_protect():
    # 给整个蓝本增加登录保护
    pass

@backend_bp.route('/')
def record():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['FIMAN_RECORD_PER_PAGE']
    pagination = Transaction.query.order_by(Transaction.timestamp.desc()).paginate(page, per_page=per_page)
    transactions = pagination.items
    return render_template('record.html', pagination = pagination, transactions=transactions)

 
@backend_bp.route('/manage')
def manage_record():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['FIMAN_RECORD_PER_PAGE']
    pagination = Transaction.query.order_by(Transaction.timestamp.desc()).paginate(page, per_page=per_page)
    transactions = pagination.items
    return render_template('backend/manage_record.html', pagination = pagination, transactions=transactions)

@backend_bp.route('/new',methods=['GET','POST'])
def new_transaction():
    import datetime
    form = PostForm()
    if form.validate_on_submit():
        pay = form.pay.data
        income = form.income.data
        balance = form.balance.data
        oppo_account = form.oppo_account.data
        oppo_name = form.oppo_name.data
        summary = form.summary.data

        account = Account.query.get(form.account_id.data)
        project = Project.query.get(form.project_id.data)
        transaction = Transaction(pay=pay, income=income, balance=balance, oppo_account=oppo_account, 
        oppo_name=oppo_name, summary=summary, account=account, project=project)
        db.session.add(transaction)
        db.session.commit()
        flash('Transaction created.', 'success')
    return render_template('backend/new_transaction.html', form=form)



@backend_bp.route('/<int:transaction_id>/edit', methods=['GET','POST'])
def edit_transaction(transaction_id):
    form = PostForm()
    print(transaction_id)
    transaction = Transaction.query.get_or_404(transaction_id)
    if form.validate_on_submit():
        # 修改Transaction字段
        transaction.pay = form.pay.data
        transaction.income = form.income.data
        transaction.balance = form.balance.data

        transaction.oppo_account = form.oppo_account.data
        transaction.oppo_name = form.oppo_name.data
        transaction.summary = form.summary.data

        transaction.account = Account.query.get(form.account_id.data)
        transaction.project = Project.query.get(form.project_id.data)

        db.session.commit()
        flash('Transaction updated.', 'success')
        return redirect(url_for('backend.manage_record', transaction_id=transaction.id))
    form.pay.data = transaction.pay
    form.income.data = transaction.income
    form.balance.data = transaction.balance

    form.oppo_account.data = transaction.oppo_account
    form.oppo_name.data = transaction.oppo_name
    form.summary.data = transaction.summary

    form.account_id.data = transaction.account.id
    form.project_id.data = transaction.project.id

    return render_template('backend/edit_transaction.html', form=form)


@backend_bp.route('/<int:transaction_id>/delete', methods=['POST'])
def delete_transaction(transaction_id):
    transaction = Transaction.query.get_or_404(transaction_id)
    db.session.delete(transaction)
    db.session.commit()
    flash('Transaction deleted.', 'success')
    return redirect_back()

fiman/templates/backend/edit_transaction.html
{% extends 'base.html'%}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}

<div class="page-header">
    <h1>Edit Transaction</h1>
</div>
{{render_form(form)}}

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{url_for('static', filename='ckeditor/ckeditor.js')}}"></script>
{% endblock %}

fiman/templates/backend/manage_record.html
{% extends "base.html"%}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block content %}
<div class="page-header">
    <h1>Transactions
        <small class="text-muted">{{pagination.total}}</small>
        <span class="float-right"><a class="btn" href="{{url_for('backend.new_transaction')}}">New Transaction</a></span>
    </h1>
</div>
    
    {% if transactions %}
    <table>
        <thead>
            <tr>
                <td>时间</td>
                <td>内容摘要</td>
                <td>支出</td>
                <td>收入</td>
                <td>项目ID</td>
                <td>账户简称</td>
                <td>对方户名</td>
                <td>对方账户</td>
            </tr>
        </thead>
        {% for transaction in transactions %}
        <tr>
            <td>{{transaction.timestamp}}</td>
            <td>{{transaction.summary}}</td>
            <td>{{transaction.pay}}</td>
            <td>{{transaction.income}}</td>
            <td>{{transaction.project_id}}</td>
            <td>{{transaction.account.abbr}}</td>
            <td>{{transaction.oppo_name}}</td>
            <td>{{transaction.oppo_account}}</td>

            <td><a class='btn' href="{{url_for('backend.edit_transaction', transaction_id = transaction.id)}}">Edit</a>
                <form class="inline" method="post"
                action="{{url_for('backend.delete_transaction', transaction_id = transaction.id, next=request.full_path)}}">
                    <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
                    <button type="submit" class="btn" onclick="return confirm('Are you sure?');">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    <div class="page-footer">{{ render_pagination(pagination) }}</div>
    {% else %}
    <div class="tip"><h5>No posts.</h5></div>
    {% endif %}

{% endblock content %}

fiman/templates/backend/new_transaction.html
{% extends 'base.html'%}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}

<div class="page-header">
    <h1>New Transaction</h1>
</div>
{{render_form(form)}}

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{url_for('static', filename='ckeditor/ckeditor.js')}}"></script>
{% endblock %}