fiman/blueprints/auth.py
from flask import Blueprint, render_template, request, current_app, flash, redirect, url_for
from flask_login import current_user, login_user, login_required, logout_user

from fiman.utils import redirect_back
from fiman.forms import LoginForm
from fiman.models import Admin, Transaction

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['POST','GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('backend.record'))
    
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.first()
        if admin:
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)
                flash('Welcome back.', 'info')
                return redirect_back() # 返回上一页面
            flash('Invalid username or password.', 'warning')
        else:
            flash('No account.', 'warning')
    return render_template('auth/login.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('front.index'))

fiman/blueprints/front.py
from flask import Blueprint, render_template, request, current_app, flash, redirect, url_for
from flask_login import current_user, login_user, login_required, logout_user

from fiman.utils import redirect_back
from fiman.forms import LoginForm
from fiman.models import Admin, Transaction

front_bp = Blueprint('front', __name__)


@front_bp.route('/')
def index():
    return render_template('front.html')

fiman/templates/base.html
<!DOCTYPE html>
<html lang="zh_CN">
<head>
    {% block header %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link ref="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
    <link ref="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}">

    {% endblock header%}
</head>
<body>
    {% block nav %}
    {% endblock nav %}
    <main class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
        {% endfor %}
        {% block content %}
        {% endblock content %}
    
        {% block footer %}
        <footer>
            <p class="float-left">
                <small> &copy; 2021 Axah</small>
            </p>
            <p>
                <small>
                    本项目参考Grey Li的项目：
                    <a href="http://greyli.com" title="Written by Grey Li">Grey Li</a> -
                    <a href="https://github.com/greyli/bluelog" title="Fork me on GitHub">GitHub</a> -
                    <a href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
                </small>
            </p>
            <p class="float-right">
                <small>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
                    {% endif %}
                </small>
            </p>
        </footer>
        {% endblock footer %}
    </main>
    
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.2.1.slim.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    {% block script %}
    {% endblock script %}
    
</body>
</html>

fiman/templates/front.html
{% extends "base.html" %}

{% block content %}
    首页
    <div>
        <a href="{{url_for('backend.record')}}">后台入口</a>

    </div>    

{% endblock %}

fiman/templates/record.html
{% extends "base.html" %}
{% from 'bootstrap/pagination.html' import render_pager %}

{% block content %}


{% if transactions %}
<table>
    <tr>
        <td>时间</td>
        <td>内容摘要</td>
        <td>支出</td>
        <td>收入</td>
        <td>项目ID</td>
        <td>账户简称</td>
        <td>对方户名</td>
        <td>对方账户</td>
    </tr>
    {% for transaction in transactions %}
    <tr>
        <td>{{transaction.timestamp}}</td>
        <td>{{transaction.summary}}</td>
        <td>{{transaction.pay}}</td>
        <td>{{transaction.income}}</td>
        <td>{{transaction.project_id}}</td>
        <td>{{transaction.account.abbr}}</td>
        <td>{{transaction.oppo_name}}</td>
        <td>{{transaction.oppo_account}}</td>
    </tr>
    {% endfor %}
</table>

{% endif %}

{% if transactions %}
    <div class="page-footer">{{ render_pager(pagination) }}</div>
{% endif %}

{% endblock content %}